version: '2'

services:
    db:
        image: 'postgres'
        ports:
            - "5432:5432"

    db_admin:
        image: 'moritanosuke/docker-pgweb'
        ports:
            - "8080:8081"
        links:
            - db
        environment:
            - POSTGRES=db
