FROM ubuntu:16.04

run apt-get update
RUN apt-get install -y git
RUN apt-get isntall -y cmake
RUN apt-get isntall -y g++
RUN apt-get isntall -y libboost-all-dev
RUN apt-get isntall -y openjdk-8-jdk
RUN apt-get isntall -y libssl-dev
RUN apt-get isntall -y libsqlite3-dev
RUN apt-get isntall -y libgraphviz-dev
RUN apt-get isntall -y libmagic-dev
RUN apt-get isntall -y libgit2-dev
RUN apt-get isntall -y npm

# apt-get install -y build-essential && \
# apt-get isntall -y llvm && \
# apt-get install -y clang-3.8 && \
# apt-get install -y cmake
